name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - run: pip install pipenv && pipenv install --dev
        working-directory: starter/backend
      - run: pipenv run lint
        working-directory: starter/backend

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - run: pip install pipenv && pipenv install --dev
        working-directory: starter/backend
      - run: pipenv run test
        working-directory: starter/backend

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - run: pip install pipenv && pipenv install --dev
        working-directory: starter/backend
      - run: pipenv run test
        working-directory: starter/backend
      - run: docker build --tag=backend:latest .
        working-directory: starter/backend
