name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - run: pip install pipenv && pipenv install --dev
        working-directory: starter/backend
      - run: pipenv run lint
        working-directory: starter/backend

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - run: pip install pipenv && pipenv install --dev
        working-directory: starter/backend
      - run: pipenv run test
        working-directory: starter/backend

  deploy:
    name: Deploys backend 
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - run: pip install pipenv && pipenv install --dev
      - run: pipenv run test
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v1
      - run: |
          docker build -t backend:${GITHUB_SHA::7} .
          docker tag backend:${GITHUB_SHA::7} ${{ secrets.BACKEND_URL }}:${GITHUB_SHA::7}
          docker push ${{ secrets.BACKEND_URL }}:${GITHUB_SHA::7}
      - run: aws eks update-kubeconfig --name cluster --region us-east-1
      - run: |
          kustomize edit set image backend=${{ secrets.BACKEND_URL }}:${GITHUB_SHA::7}
          kustomize build | kubectl apply -f -
        working-directory: starter/backend/k8s

