name: Frontend CD

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      - run: npm ci
        working-directory: starter/frontend
      - run: npm run lint
        working-directory: starter/frontend

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      - run: npm ci
        working-directory: starter/frontend
      - run: CI=true npm test
        working-directory: starter/frontend

  deploy:
    name: Deploys Frontend
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      - run: npm install
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v1
      - run: |
          docker build --build-arg REACT_APP_MOVIE_API_URL=${{ secrets.BACKEND_URL }} -t frontend:${GITHUB_SHA::7} .
          docker tag frontend:${GITHUB_SHA::7} ${{ secrets.FRONTEND_URL }}:${GITHUB_SHA::7}
          docker push ${{ secrets.FRONTEND_URL }}:${GITHUB_SHA::7}
      - run: aws eks update-kubeconfig --name cluster --region us-east-1
      - run: |
          cd k8s
          kustomize edit set image frontend=${{ secrets.FRONTEND_URL }}:${GITHUB_SHA::7}
          kustomize build | kubectl apply -f -
